//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muestra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class muestraEntities1 : DbContext
    {
        public muestraEntities1()
            : base("name=muestraEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<imagenes> imagenes { get; set; }
        public virtual DbSet<pagina> pagina { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<visitas> visitas { get; set; }
    }
}
